--Clean the db before initializing the configuration for TESTING
--DO NOT EXECUTE ON PRODUCTION

--External Schema
IF EXISTS(SELECT 'Exists' FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SaleDetail')
	TRUNCATE TABLE [External].[SaleDetail]
GO

IF EXISTS(SELECT 'Exists' FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Sale')
	DELETE FROM [External].[Sale]
GO

--IF EXISTS(SELECT 'Exists' FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Product')
--BEGIN TRY
--	BEGIN TRAN

--		ALTER TABLE [External].[Product] SET (SYSTEM_VERSIONING = OFF);

--		DELETE FROM [External].[Product]
--		DELETE FROM [External].[ProductHistory]

--		ALTER TABLE [External].[Product] SET (SYSTEM_VERSIONING = ON);
--	COMMIT TRAN
--END TRY
--BEGIN CATCH	
--	SELECT ERROR_MESSAGE()
--	ROLLBACK TRAN
--END CATCH
--GO

IF EXISTS(SELECT 'Exists' FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Customer')
	TRUNCATE TABLE [External].[Customer]
GO

----Internal Schema
--IF EXISTS(SELECT 'Exists' FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Salary')
--BEGIN TRY
--	BEGIN TRAN

--		ALTER TABLE [Internal].[Salary] SET (SYSTEM_VERSIONING = OFF);

--		DELETE FROM [Internal].[Salary]
--		DELETE FROM [Internal].[SalaryHistory]

--		ALTER TABLE [Internal].[Salary] SET (SYSTEM_VERSIONING = ON);
--	COMMIT TRAN
--END TRY
--BEGIN CATCH	
--	SELECT ERROR_MESSAGE()
--	ROLLBACK TRAN
--END CATCH
--GO

--IF EXISTS(SELECT 'Exists' FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'AppUser')
--	DELETE FROM [Internal].[AppUser]
--GO