--Clean the db before initializing the configuration for TESTING
--DO NOT EXECUTE ON PRODUCTION

--External Schema
IF EXISTS(SELECT 'Exists' FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SaleDetail')
	TRUNCATE TABLE [External].[SaleDetail]

IF EXISTS(SELECT 'Exists' FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Sale')
	TRUNCATE TABLE [External].[Sale]

IF EXISTS(SELECT 'Exists' FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Product')
	TRUNCATE TABLE [External].[Product]

IF EXISTS(SELECT 'Exists' FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Customer')
	TRUNCATE TABLE [External].[Customer]

--Internal Schema
IF EXISTS(SELECT 'Exists' FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Salary')
	TRUNCATE TABLE [Internal].[Salary]

IF EXISTS(SELECT 'Exists' FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'AppUser')
	TRUNCATE TABLE [Internal].[AppUser]


