CREATE TABLE [DW].[SSISLogging]
(
	SSISLoggingId			INT IDENTITY(1,1)	NOT NULL,
	SSISLoggingDate			DATETIME2(3)		NOT NULL CONSTRAINT DF_SSISLogging_Date DEFAULT GETDATE(),
	SSISLoggingPackage		VARCHAR(50)			NOT NULL,
	SSISLoggingInformation	VARCHAR(MAX)		NOT NULL,
	CONSTRAINT PK_SSISLogging PRIMARY KEY (SSISLoggingId)
)
GO

